[package]
name = "umpl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
unic-emoji-char = "0.9.0"
hexponent = "0.3.1"