on: 
  push:
  workflow_dispatch:

name: Test examples

jobs:
  test_examples:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Test examples
        run: |
          chmod +x umpl_examples/test.sh
          ./umpl_examples/test.sh